version: '3.6'

services:
  mpd:
    build:
      context: .
    container_name: mpd
    user: "1000"
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - 8800:8800
      - 6600:6600
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PULSE_COOKIE=/tmp/pulse.cookie
    volumes:
      - ./mpd.conf:/etc/mpd.conf
      - ./music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./data:/var/lib/mpd/data
      - /run/user/1000/pulse:/run/user/1000/pulse
